/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rafael_logistic_set_mandelbrot_MandelbrotSetNativeGenerator */

#ifndef _Included_rafael_logistic_set_mandelbrot_MandelbrotSetNativeGenerator
#define _Included_rafael_logistic_set_mandelbrot_MandelbrotSetNativeGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rafael_logistic_set_mandelbrot_MandelbrotSetNativeGenerator
 * Method:    checkMandelbrotConvergence
 * Signature: (DDDDI)I
 */
JNIEXPORT jint JNICALL Java_rafael_logistic_set_mandelbrot_MandelbrotSetNativeGenerator_checkMandelbrotConvergence
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
